:green_heart: Fix IndexError due to Lake Whillans 6 disappearing
Since Subglacial Lake Whillans 6 'disappeared' in e5e91cd039e5800d7727498efa3176e61f65ea81, shouldn't use it in the integration test. Oh yes, time to get back into this ICESat-2 project! Running things on a new workstation now and there's some exciting new libraries so best to wrap this up! Fixed a `TypeError: __init__() got an unexpected keyword argument 'calc_core_sample_indices'` because of scikit-learn/cuml API differences. Also gitignoring the dask-worker-space folder and some of the vector data files.

Had to bump llvmlite from 0.36.0 to 0.38.0 in the poetry.lock file to be in line with conda installed version and prevent "ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall". Similar business with d89186ec5dc189f1dda35618d2d504beb26c7a0d.